# Generated by Django 6.0.6 on 2026-06-19 16:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('deleted_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'dj_categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('image_path', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('deleted_at', models.DateField(null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='core.tag')),
            ],
            options={
                'db_table': 'dj_products',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_gt_zero')],
            },
        ),
    ]
